# Site
repository: cmagganas/resume
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Christos Magganas
title: AI Engineer @ AI Makerspace | Founding Engineer @ Toro
website: www.github.com/cmagganas

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: christosmagg
github_username:  cmagganas
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: christos_magganas
linkedin_username: christos-magganas
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: "@cmagganas"
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: christos.app
  icon: fas fa-globe
  url: https://www.christos.app/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/greeksgiving2023.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Christos and I'm an AI Engineer at AI Makerspace and a Founding Engineer at Toro.

  I am most skilled in: <mark>Python</mark>, <mark>AI/ML Ops</mark>, and <mark>Dancing</mark>.

  I am passionate about leveraging AI and ML to address societal challenges, aiming to join a mission-driven team that encourages learning, growth, and innovation. I focus on community building and knowledge sharing, contributing as a volunteer and consultant to foster growth and collaborative problem-solving. I aspire to use my expertise for techno-philanthropic ventures, driving advancements that benefit humanity.

content:
  - title: Current Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Toro
        link: https://www.mytoro.ai/
        sub_title: Founding Engineer - Lead AI Engineer
        caption: August 2024 - Present
        quote: >
          Leading AI Research & Development for Text-Based Food Ordering
        description: | # this will include new lines to allow paragraphs
            As a Founding Engineer at Toro, I lead a team of AI engineers to develop cutting-edge AI solutions. My role involves strategic planning, project management, and hands-on development of innovative text-based food ordering systems.

      - layout: left
        title: AI Makerspace
        link: https://aimakerspace.io/
        sub_title: Community Builder & Peer Supporter
        caption: October 2023 - Present
        quote: >
          Building a community of AI enthusiasts and professionals to foster learning and collaboration.
        description: | # this will include new lines to allow paragraphs
            Facilitating "Christos' Community Creations" bi-weekly and fostering a dynamic AI/ML community. As Peer Supporter for the AI Engineering cohort, I facilitate breakout sessions, assist learners, hold office hours, and provide guidance for final projects.

  - title: Past Experience
    layout: list
    content:
      - layout: left
        title: Learvo
        sub_title: AI Engineer
        caption: September 2023 - November 2023
        description: Led design of mnemonic solutions using LangChain and LlamaIndex as LLM application architect.

      - layout: left
        title: Kaleidoscope Data
        sub_title: AI/ML Engineer
        caption: April 2023 - August 2023
        description: Developed RAG-based Reddit Bot and conducted LLM research projects.

      - layout: left
        title: Cisco
        sub_title: Data Scientist (Intern)
        caption: May 2022 - September 2022
        description: Implemented MLOps best practices and end-to-end observability solutions.

      - layout: left
        title: HCL Technologies
        sub_title: Data Analyst (Google Cloud Platform)
        caption: March 2021 - September 2021
        description: Built dashboards and performed ETL tasks improving team efficiency by ~10%.

  - title: Recent Education
    layout: list
    content:
      - layout: left
        title: AI Makerspace
        caption: August 2023 - November 2023
        sub_title: LLM Engineering & Operations
        description: | # this will include new lines to allow paragraphs
            Mastered LLM product development using LangChain and LlamaIndex frameworks, contributing to open-source projects and building end-to-end Generative AI applications.

      - layout: left
        title: FourthBrain
        caption: December 2022 - May 2023
        sub_title: Machine Learning Engineer
        description: | # this will include new lines to allow paragraphs
            Specialized in Data-centric AI, ML Modeling, AI Applications, and MLOps. Built and deployed LLM applications using various frameworks and fine-tuning techniques.

  - title: Additional Education
    layout: list
    content:
      - layout: left
        title: University of California, Santa Barbara
        caption: 2017
        sub_title: B.S. Actuarial Science
        description: | # this will include new lines to allow paragraphs
          Developed strong foundation in mathematical and statistical methods for analyzing financial risks.

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Real-time Multilingual Custom Keyword Spotting
        link: github.com/cmagganas
        additional_links:
          - title:  cmagganas/real-time-multilingual-custom-keyword-spotting
            icon: fab fa-github
            url: github.com/cmagganas/real-time-multilingual-custom-keyword-spotting
        quote: >
          Developed a lightweight few-shot learning model for personalization of keyword spotting or wake-word detection.
        description: | # this will include new lines to allow paragraphs
          This project was a significant milestone in my career, allowing me to apply my skills in <mark>AI</mark> and <mark>ML</mark> to create a practical solution for real-world applications.

      - layout: top-middle
        title: Spotify Playlist Recommender
        link: github.com/cmagganas
        additional_links:
          - title:  cmagganas/spotify-playlist-recommender
            icon: fab fa-github
            url: github.com/cmagganas/spotify-playlist-recommender
        quote: >
          Developed a Spotify App that takes user's music taste to recommend songs and create a playlist for them using Spotify's Web API.
        description: | # this will include new lines to allow paragraphs
          This project allowed me to explore the integration of AI with music, creating a personalized experience for users by leveraging Spotify's Web API.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in AI/ML, software engineering and community building, some of my other interests and hobbies are:
      - Rock climbing
      - Yoga
      - Dancing
      - Stoicism
      - Entrepreneurship
      - Techno-Philanthropy

      This is an image from one of my favorite movies, *Castle in the Sky*. It inspires me to always follow my heart, be courageous, and never give up on my dreams.
      ![Castle in the Sky](/resume/images/castle-in-the-sky.jpeg "Castle in the Sky")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
