# Site
repository: cmagganas/resume
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Christos Magganas
title: AI Engineer @ AI Makerspace | Founding Engineer @ Toro
# website: www.github.com/cmagganas

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: christosmagg
github_username:  cmagganas
instagram_username: christos_magganas
linkedin_username: christos-magganas
youtube_username: "@cmagganas"
# Additional icon links
additional_links:
- title: christos.app
  icon: fas fa-globe
  url: https://www.christos.app/

# About Section
# about_title: About Me
about_profile_image: images/greeksgiving2023.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Christos and I'm an AI Engineer at AI Makerspace and a Founding Engineer at Toro.

  I am most skilled in: <mark>Python</mark>, <mark>AI/ML Ops</mark>, and <mark>Dancing</mark>.

  I am passionate about leveraging AI and ML to address societal challenges, aiming to join a mission-driven team that encourages learning, growth, and innovation. I focus on community building and knowledge sharing, contributing as a volunteer and consultant to foster growth and collaborative problem-solving. I aspire to use my expertise for techno-philanthropic ventures, driving advancements that benefit humanity.

content:
  - title: Current Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Toro
        link: https://www.mytoro.ai/
        sub_title: Founding Engineer - Lead AI Engineer
        caption: August 2024 - Present
        quote: >
          Leading AI Research & Development for Text-Based Food Ordering
        description: | # this will include new lines to allow paragraphs
            As a Founding Engineer at Toro, I lead a team of AI engineers to develop cutting-edge AI solutions. My role involves strategic planning, project management, and hands-on development of innovative text-based food ordering systems.

      - layout: left
        title: AI Makerspace
        link: https://aimakerspace.io/
        sub_title: Community Builder & Peer Supporter
        caption: October 2023 - Present
        quote: >
          Building a community of AI enthusiasts and professionals to foster learning and collaboration.
        description: | # this will include new lines to allow paragraphs
            Facilitating "Christos' Community Creations" bi-weekly and fostering a dynamic AI/ML community. As Peer Supporter for the AI Engineering cohort, I facilitate breakout sessions, assist learners, hold office hours, and provide guidance for final projects.

  - title: Education
    layout: list
    content:
      - layout: left
        title: AI Makerspace
        caption: August 2023 - November 2023
        sub_title: LLM Engineering & Operations
        description: | # this will include new lines to allow paragraphs
            Mastered LLM product development using LangChain and LlamaIndex frameworks, contributing to open-source projects and building end-to-end Generative AI applications.

      - layout: left
        title: FourthBrain
        caption: December 2022 - May 2023
        sub_title: Machine Learning Engineer
        description: | # this will include new lines to allow paragraphs
            Specialized in Data-centric AI, ML Modeling, AI Applications, and MLOps. Built and deployed LLM applications using various frameworks and fine-tuning techniques.

      - layout: left
        title: University of California, Santa Barbara
        caption: 2017
        sub_title: B.S. Actuarial Science
        description: | # this will include new lines to allow paragraphs
          Developed strong foundation in mathematical and statistical methods for analyzing financial risks.

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: LLM Observability with Arize Phoenix and LlamaIndex
        link: github.com/cmagganas
        additional_links:
          - title: LLM Observability with Arize Phoenix and LlamaIndex
            icon: fab fa-youtube
            url: LLM Observability with Arize Phoenix and LlamaIndex
        quote: >
          Built a framework for bringing transparency and control to LLM observability using Arize Phoenix and LlamaIndex.
        description: | # this will include new lines to allow paragraphs
          Led an AI Makerspace Community Build Session focused on evaluating AI model performance, leveraging retrieval-augmented generation, and interpreting metrics for model improvement. The project emphasized data evaluation, Chain of Thought analysis, and best practices for debugging LLM applications.

      - layout: top-middle
        title: Best Practices for Coding with LLMs
        link: github.com/cmagganas/cursor-best-practices-demo
        additional_links:
          - title: Best Practices for Coding with LLMs
            icon: fab fa-youtube
            url: https://youtu.be/eL1Bt1dgDkc
          - title: GitHub Presentation
            icon: fab fa-globe
            url: https://voxel51.com/computer-vision-events/nov-20-san-francisco-ai-ml-amp-computer-vision-meetup/
        quote: >
          Developed and presented comprehensive guidelines for effectively utilizing LLMs in software development workflows.
        description: | # this will include new lines to allow paragraphs
          Led an AI Makerspace Community Session on best practices for coding with LLMs, with a focus on practical implementation using Cursor. Presented findings at GitHub's San Francisco AI/ML & Computer Vision Meetup, demonstrating effective techniques for leveraging AI assistance in software development while maintaining code quality.

      - layout: top-middle
        title: Real-time Multilingual Custom Keyword Spotting
        link: github.com/cmagganas
        additional_links:
          - title:  cmagganas/real-time-multilingual-custom-keyword-spotting
            icon: fab fa-github
            url: github.com/cmagganas/real-time-multilingual-custom-keyword-spotting
        quote: >
          Developed a lightweight few-shot learning model for personalization of keyword spotting or wake-word detection.
        description: | # this will include new lines to allow paragraphs
          This project was a significant milestone in my career, allowing me to apply my skills in <mark>AI</mark> and <mark>ML</mark> to create a practical solution for real-world applications.

      - layout: top-middle
        title: Spotify Playlist Recommender
        link: github.com/cmagganas
        additional_links:
          - title:  cmagganas/spotify-playlist-recommender
            icon: fab fa-github
            url: github.com/cmagganas/spotify-playlist-recommender
        quote: >
          Developed a Spotify App that takes user's music taste to recommend songs and create a playlist for them using Spotify's Web API.
        description: | # this will include new lines to allow paragraphs
          This project allowed me to explore the integration of AI with music, creating a personalized experience for users by leveraging Spotify's Web API.

  - title: Past Experience
    layout: list
    content:
      - layout: left
        title: Learvo
        sub_title: AI Engineer
        caption: September 2023 - November 2023
        description: Led design of mnemonic solutions using LangChain and LlamaIndex as LLM application architect.

      - layout: left
        title: Kaleidoscope Data
        sub_title: AI/ML Engineer
        caption: April 2023 - August 2023
        description: Developed RAG-based Reddit Bot and conducted LLM research projects.

      - layout: left
        title: Cisco
        sub_title: Data Scientist (Intern)
        caption: May 2022 - September 2022
        description: Implemented MLOps best practices and end-to-end observability solutions.

      - layout: left
        title: HCL Technologies
        sub_title: Data Analyst (Google Cloud Platform)
        caption: March 2021 - September 2021
        description: Built dashboards and performed ETL tasks improving team efficiency by ~10%.

      - layout: left
        title: Commercial Energy of California
        sub_title: Data Analyst
        caption: September 2019 - November 2020
        description: Led initiative to automate manual analyses and reports, improving efficiency and increasing revenue.

      - layout: left
        title: Property Management & Development
        sub_title: Manager
        caption: September 2013 - Current
        description: Managed 10+ residential/commercial properties and supervised construction projects with 10+ workers.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in AI/ML, software engineering and community building, some of my other interests and hobbies are:
      - Rock climbing
      - Yoga
      - Dancing
      - Stoicism
      - Entrepreneurship
      - Techno-Philanthropy

      This is an image from one of my favorite movies, *Castle in the Sky*. It inspires me to always follow my heart, be courageous, and never give up on my dreams.
      ![Castle in the Sky](/resume/images/castle-in-the-sky.jpeg "Castle in the Sky")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
